import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/product.component.css"
import "../styles/header.component.css"
import "../styles/category.component.css"
import "../styles/common.component.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
